import express, { Express } from "express";
import path from "path";
import { createSsrServer } from "vite-ssr/dev";
import { ConfigProvider, TrainQuery, trainQuery } from "./ctx/trainquery";
import { OnlineConfigProvider } from "./config/online-config-provider";
import { ExpressServer } from "./ctx/express-server";
import "dotenv/config";
import { OfflineConfigProvider } from "./config/offline-config-provider";
import { ssrAppPropsApi } from "./api/ssr-props-api";
import { TrainQueryDB } from "./ctx/trainquery-db";
import { createSitemapXml } from "./sitemap-xml";
import { EnvironmentVariables } from "./ctx/environment-variables";
import { EnvironmentOptions } from "./ctx/environment-options";
import { AdminLogger } from "./ctx/admin-logger";

createServer();

async function createServer() {
  const instanceID = generateInstanceID();

  const isProd = EnvironmentVariables.get().isProduction();
  const envOptions = await getEnvironmentOptions(isProd);

  const logger = new AdminLogger(instanceID, envOptions.logging);
  logger.logInstanceStarting(instanceID);
  logger.logEnvOptions(envOptions);

  const isOffline = process.argv.includes("offline");
  const useOfflineData =
    process.argv.includes("offline-data") ||
    process.argv.includes("data-offline");
  const port = EnvironmentVariables.get().port;

  const serveFrontend = async (ctx: TrainQuery, app: Express) => {
    if (isProd) {
      await setupProdServer(ctx, app);
    } else {
      await setupDevServer(ctx, app);
    }
  };

  await trainQuery(
    instanceID,
    () => new ExpressServer(port, serveFrontend),
    getConfigProvider(isOffline || useOfflineData),
    getDatabase(isOffline),
    logger,
    isOffline,
    isProd,
  );
}

async function getEnvironmentOptions(isProd: boolean) {
  const index = process.argv.findIndex((x) => x === "--env");
  if (index === -1) {
    return EnvironmentOptions.default(isProd);
  }

  let name = process.argv.length >= index + 2 ? process.argv[index + 1] : null;
  if (name === null) {
    throw new Error(`Missing environment name after "--env".`);
  }

  if (name === "file") {
    name = ".env-options.json";
  }

  if (name.endsWith(".json")) {
    try {
      return await EnvironmentOptions.loadFromFile(name);
    } catch {
      throw new Error(`Failed to load environment from file "${name}".`);
    }
  } else {
    const env = EnvironmentOptions.loadFromName(name);
    if (env == null) {
      throw new Error(`Unknown environment name "${name}".`);
    }
    return env;
  }
}

function getConfigProvider(useOfflineData: boolean): ConfigProvider {
  const canonicalUrl = EnvironmentVariables.get().url;
  if (useOfflineData) {
    const zipOrFolderPath = EnvironmentVariables.get().requireConfigOffline();
    return new OfflineConfigProvider(zipOrFolderPath, canonicalUrl);
  } else {
    const configUrl = EnvironmentVariables.get().config;
    return new OnlineConfigProvider(configUrl, canonicalUrl);
  }
}

function getDatabase(isOffline: boolean): TrainQueryDB | null {
  if (isOffline) {
    return null;
  }

  const mongo = EnvironmentVariables.get().mongo;
  if (mongo == null) {
    return null;
  }
  return new TrainQueryDB(mongo.domain, mongo.username, mongo.password);
}

async function setupDevServer(ctx: TrainQuery, app: Express) {
  serveSitemapXml(app, ctx);

  // Create vite-ssr server in middleware mode.
  const viteServer = await createSsrServer({
    server: { middlewareMode: true },
    appType: "custom",
  });
  app.use(viteServer.middlewares);
}

async function setupProdServer(ctx: TrainQuery, app: Express) {
  serveSitemapXml(app, ctx);

  const dist = `../dist`;

  // Serve static assets.
  const { ssr } = require(`${dist}/server/package.json`);
  for (const asset of ssr.assets || []) {
    const serverEndpoint = "/" + asset;
    const distFolderPath = path.join(__dirname, `${dist}/client/` + asset);
    app.use(serverEndpoint, express.static(distFolderPath));
  }

  // Render the pages, as generated by vite-ssr.
  const manifest = require(`${dist}/client/ssr-manifest.json`);
  const renderPage = (await import(`${dist}/server/main.js`)).default.default;
  app.get("*", async (req, res) => {
    const url = req.protocol + "://" + req.get("host") + req.originalUrl;

    const { html, status, statusText, headers } = await renderPage(url, {
      manifest,
      preload: true,
      request: req,
      response: res,
      initialState: { props: await ssrAppPropsApi(ctx) },
    });

    res.type("html");
    res.writeHead(status || 200, statusText || headers, headers);
    res.end(html);
  });
}

function serveSitemapXml(app: Express, ctx: TrainQuery) {
  app.get("/sitemap.xml", (_req, res) => {
    const xml = createSitemapXml(ctx.getConfig());
    res.set("Content-Type", "text/xml").send(xml);
  });
}

function generateInstanceID(): string {
  return crypto
    .getRandomValues(new Uint8Array(4))
    .reduce((str, x) => str + x.toString(16).padStart(2, "0"), "");
}
